[package]
name = "ipl_cli"
version = "0.1.0"
edition = "2021"
description = "Command line interface for the Impossible Programming Language (IPL)"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
toml = "0.8"
which = "4.4"
